export const FETCH_SINGLE_ITEM_REQUEST = 'FETCH_SINGLE_ITEM_REQUEST';
export const FETCH_SINGLE_ITEM_SUCCESS = 'FETCH_SINGLE_ITEM_SUCCESS';
export const FETCH_SINGLE_ITEM_FAILURE = 'FETCH_SINGLE_ITEM_FAILURE';