export const FETCH_CHECKOUT_ITEMS_REQUEST = 'FETCH_CHECKOUT_ITEMS_REQUEST';
export const FETCH_CHECKOUT_ITEMS_SUCCESS = 'FETCH_CHECKOUT_ITEMS_SUCCESS';
export const FETCH_CHECKOUT_ITEMS_FAILURE = 'FETCH_CHECKOUT_ITEMS_FAILURE';